---
version: "3"
services:
  mq01:
    image: "rabbitmq:3.8.7-management"
    container_name: 'mq01.rabbit.ops'
    hostname: 'mq01.rabbit.ops'
    environment:
      RABBITMQ_ERLANG_COOKIE: 'ah38qsb2qH242rd'
      RABBITMQ_NODE_NAME: 'mq01.rabbit.ops'
      RABBITMQ_USE_LONGNAME: "true"
    ports:
      - '5672:5672'
      - '5671:5671'
      - '15672:15672'
      - '15671:15671'
      - '4369:4369'
      - '25672'
      - '25671'
    volumes:
      - "./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - "./config/tls/ca.bundle.pem:/etc/rabbitmq/ca.bundle.pem"
      - "./config/tls/mq01/mq01.rabbit.ops.crt.pem:/etc/rabbitmq/server.rabbit.ops.crt.pem:ro"
      - "./config/tls/mq01/mq01.rabbit.ops.key.pem:/etc/rabbitmq/server.rabbit.ops.key.pem:ro"
      - "./config/tls/client.rabbit.ops.crt.pem:/etc/rabbitmq/client.rabbit.ops.crt.pem:ro"
      - "./config/tls/client.rabbit.ops.key.pem:/etc/rabbitmq/client.rabbit.ops.key.pem:ro"
      - "./config/inter_node_tls.config:/etc/rabbitmq/inter_node_tls.config"
      - "./config/rabbitmq-env.conf:/etc/rabbitmq/rabbitmq-env.conf"
      - "./config/tls/management.rabbit.ops.crt.pem:/etc/rabbitmq/management.rabbit.ops.crt.pem:ro"
      - "./config/tls/management.rabbit.ops.key.pem:/etc/rabbitmq/management.rabbit.ops.key.pem:ro"

  mq02:
    image: rabbitmq:3.8.7-management
    container_name: 'mq02.rabbit.ops'
    hostname: 'mq02.rabbit.ops'
    environment:
      RABBITMQ_ERLANG_COOKIE: 'ah38qsb2qH242rd'
      RABBITMQ_NODE_NAME: 'mq02.rabbit.ops'
      RABBITMQ_USE_LONGNAME: "true"
    command: ["/tmp/wait-for.sh"]
    ports:
      - '5672'
      - '15672'
      - '4369'
      - '25672'
      - '25671'
    volumes:
      - "./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - "./wait-for.sh:/tmp/wait-for.sh"
      - "./config/tls/ca.bundle.pem:/etc/rabbitmq/ca.bundle.pem"
      - "./config/tls/mq02/mq02.rabbit.ops.crt.pem:/etc/rabbitmq/server.rabbit.ops.crt.pem:ro"
      - "./config/tls/mq02/mq02.rabbit.ops.key.pem:/etc/rabbitmq/server.rabbit.ops.key.pem:ro"
      - "./config/tls/client.rabbit.ops.crt.pem:/etc/rabbitmq/client.rabbit.ops.crt.pem:ro"
      - "./config/tls/client.rabbit.ops.key.pem:/etc/rabbitmq/client.rabbit.ops.key.pem:ro"
      - "./config/inter_node_tls.config:/etc/rabbitmq/inter_node_tls.config"
      - "./config/rabbitmq-env.conf:/etc/rabbitmq/rabbitmq-env.conf"
      - "./config/tls/management.rabbit.ops.crt.pem:/etc/rabbitmq/management.rabbit.ops.crt.pem:ro"
      - "./config/tls/management.rabbit.ops.key.pem:/etc/rabbitmq/management.rabbit.ops.key.pem:ro"

  mq03:
    image: rabbitmq:3.8.7-management
    container_name: 'mq03.rabbit.ops'
    hostname: 'mq03.rabbit.ops'
    environment:
      RABBITMQ_ERLANG_COOKIE: 'ah38qsb2qH242rd'
      RABBITMQ_NODE_NAME: 'mq03.rabbit.ops'
      RABBITMQ_USE_LONGNAME: "true"
    command: ["/tmp/wait-for.sh"]
    ports:
      - '5672'
      - '15672'
      - '4369'
      - '25672'
      - '25671'
    volumes:
      - "./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - "./wait-for.sh:/tmp/wait-for.sh"
      - "./config/tls/ca.bundle.pem:/etc/rabbitmq/ca.bundle.pem"
      - "./config/tls/mq03/mq03.rabbit.ops.crt.pem:/etc/rabbitmq/server.rabbit.ops.crt.pem:ro"
      - "./config/tls/mq03/mq03.rabbit.ops.key.pem:/etc/rabbitmq/server.rabbit.ops.key.pem:ro"
      - "./config/tls/client.rabbit.ops.crt.pem:/etc/rabbitmq/client.rabbit.ops.crt.pem:ro"
      - "./config/tls/client.rabbit.ops.key.pem:/etc/rabbitmq/client.rabbit.ops.key.pem:ro"
      - "./config/inter_node_tls.config:/etc/rabbitmq/inter_node_tls.config"
      - "./config/rabbitmq-env.conf:/etc/rabbitmq/rabbitmq-env.conf"
      - "./config/tls/management.rabbit.ops.crt.pem:/etc/rabbitmq/management.rabbit.ops.crt.pem:ro"
      - "./config/tls/management.rabbit.ops.key.pem:/etc/rabbitmq/management.rabbit.ops.key.pem:ro"
