---
version: "3"
services:
  rabbitmq1:
    image: rabbitmq:3.8.5-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: 'ah38qsb2qH242rd'
      RABBITMQ_NODE_NAME: 'rabbitmq1'
    ports:
      - '5672'
      - '15672:15672'
      - '4369:4369'
      - '35672-35682'
      - '25672'
    volumes:
      - "./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"

  rabbitmq2:
    image: rabbitmq:3.8.5-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    environment:
      RABBITMQ_ERLANG_COOKIE: 'ah38qsb2qH242rd'
      RABBITMQ_NODE_NAME: 'rabbitmq2'
    ports:
      - '5672'
      - '15672'
      - '4369'
      - '35672-35682'
      - '25672'
    volumes:
      - "./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"

  rabbitmq3:
    image: rabbitmq:3.8.5-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    environment:
      RABBITMQ_ERLANG_COOKIE: 'ah38qsb2qH242rd'
      RABBITMQ_NODE_NAME: 'rabbitmq3'
    ports:
      - '5672'
      - '15672'
      - '4369'
      - '35672-35682'
      - '25672'
    volumes:
      - "./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
